# Generated by Django 5.2.6 on 2025-12-12 18:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editorprofile',
            name='last_activity',
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('facebook', 'Facebook'), ('github', 'GitHub'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('twitter', 'Twitter'), ('youtube', 'YouTube')], max_length=64)),
                ('url', models.URLField(unique=True, validators=[django.core.validators.URLValidator(), django.core.validators.RegexValidator(regex='^(https?://)?(www\\.)?(github\\.com|twitter\\.com|x\\.com|linkedin\\.com|instagram\\.com|facebook\\.com|youtube\\.com|tiktok\\.com)/.+$')])),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='users.editorprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='SocialAccounts',
        ),
    ]
