# Generated by Django 5.2.6 on 2025-12-31 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_change_related_name_to_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='name',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('github', 'GitHub'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('twitter', 'Twitter'), ('x', 'X'), ('youtube', 'YouTube')], max_length=64),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.URLField(validators=[django.core.validators.RegexValidator(regex='^https://(www\\.)?(github\\.com|twitter\\.com|x\\.com|linkedin\\.com|instagram\\.com|facebook\\.com|youtube\\.com|tiktok\\.com)/.+$')]),
        ),
        migrations.AlterUniqueTogether(
            name='sociallink',
            unique_together={('profile', 'url')},
        ),
        migrations.AddIndex(
            model_name='sociallink',
            index=models.Index(fields=['profile', 'name'], name='users_socia_profile_c06551_idx'),
        ),
    ]
