# Generated by Django 5.2.6 on 2025-12-12 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('uploads', '0005_alter_upload_file_alter_upload_hash_md5_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='draft', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('content', models.TextField(blank=True)),
                ('summary', models.CharField(blank=True, max_length=250)),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('attachments', models.ManyToManyField(blank=True, related_name='post_attachments', to='uploads.upload')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='content.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='content.tag')),
                ('thumbnail', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_thumbnail', to='uploads.upload')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status'], name='content_pos_status_94dfa7_idx'), models.Index(fields=['category'], name='content_pos_categor_092e2d_idx')],
            },
        ),
    ]
