# Generated by Django 5.2.6 on 2025-12-12 18:50

import apps.uploads.utils.path
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_upload_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(max_length=250, upload_to=apps.uploads.utils.path.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp4', 'mov', 'avi', 'mp3', 'wav', 'doc', 'docx', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='upload',
            name='hash_md5',
            field=models.CharField(blank=True, editable=False, max_length=32, validators=[django.core.validators.RegexValidator('^[a-fA-F0-9]{32}$')]),
        ),
        migrations.AlterField(
            model_name='upload',
            name='purpose',
            field=models.CharField(choices=[('avatars', 'Avatars'), ('thumbnails', 'Thumbnails'), ('attachments', 'Attachments')], default='attachments', max_length=20),
        ),
    ]
