# Generated by Django 5.2.6 on 2026-01-22 05:01

import apps.uploads.utils.path
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0006_alter_upload_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='upload',
            name='uploads_upl_hash_md_73d199_idx',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='hash_md5',
        ),
        migrations.AddField(
            model_name='upload',
            name='hash_sha256',
            field=models.CharField(default=2, editable=False, max_length=64, validators=[django.core.validators.RegexValidator('^[a-fA-F0-9]{64}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(max_length=250, upload_to=apps.uploads.utils.path.get_upload_path),
        ),
        migrations.AlterField(
            model_name='upload',
            name='original_filename',
            field=models.CharField(max_length=250),
        ),
        migrations.AddIndex(
            model_name='upload',
            index=models.Index(fields=['hash_sha256'], name='uploads_upl_hash_sh_c6e211_idx'),
        ),
    ]
