services:
  db:
    image: mariadb:lts
    container_name: simple_drf_blog-dev-mariadb
    restart: unless-stopped
    env_file:
      - ../envs/.env.dev.db
    ports:
      - "3306:3306"
    volumes:
      - mariadb_dev:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: simple_drf_blog-dev-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    image: simple_drf_blog:latest
    container_name: simple_drf_blog-dev-web
    build:
      context: ..
      dockerfile: docker/dockerfile.dev
    restart: unless-stopped
    working_dir: /app/src
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.development
    ports:
      - "8000:8000"
    volumes:
      - ..:/app
      - venv_data:/app/.venv
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: >
      sh -c "
        until python manage.py check --database default 2>/dev/null; do
          echo 'Waiting for the database...';
          sleep 2;
        done;
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "

  celery_worker:
    image: simple_drf_blog:latest
    container_name: simple_drf_blog-dev-celery_worker
    restart: unless-stopped
    working_dir: /app/src
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.development
    volumes:
      - ..:/app
      - venv_data:/app/.venv
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: >
      sh -c "celery -A config worker -l info"

volumes:
  mariadb_dev:
  venv_data:
