FROM python:3.12-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    pkg-config \
    libmariadb-dev \
    libmagic1 \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir uv

RUN useradd --create-home --no-log-init app-user

WORKDIR /app

RUN mkdir -p .venv && chown app-user:app-user .venv

USER app-user

WORKDIR /app

COPY --chown=app-user:app-user pyproject.toml uv.lock ./

COPY --chown=app-user:app-user docker/entrypoint.dev.sh /app/docker/entrypoint.dev.sh

RUN chmod +x /app/docker/entrypoint.dev.sh

ENTRYPOINT ["/app/docker/entrypoint.dev.sh"]

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PATH="/app/.venv/bin:$PATH" \
    DJANGO_SETTINGS_MODULE="config.settings.development"

CMD ["python3", "src/manage.py", "runserver", "0.0.0.0:8000"]
