FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    pkg-config \
    libmariadb-dev \
    libmagic1

RUN pip install uv

WORKDIR /app

COPY pyproject.toml uv.lock ./

RUN uv sync --frozen

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PATH="/app/.venv/bin:$PATH" \
    DJANGO_SETTINGS_MODULE="config.settings.development"

CMD ["python3", "src/manage.py", "runserver", "0.0.0.0:8000"]
