# Generated by Django 5.2.6 on 2026-02-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricevent',
            name='event_type',
            field=models.CharField(choices=[('post_read', 'Post Read'), ('login', 'Login'), ('upload_created', 'Upload Created'), ('login_failed', 'Login Failed')], db_index=True, max_length=64),
        ),
    ]
