# Generated by Django 5.2.6 on 2026-04-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_alter_metricevent_event_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metricevent',
            options={},
        ),
        migrations.RemoveField(
            model_name='metricevent',
            name='user',
        ),
        migrations.AlterField(
            model_name='metricevent',
            name='event_type',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
