# Generated by Django 5.2.6 on 2026-04-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_alter_metricevent_options_remove_metricevent_user_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='metricevent',
            index=models.Index(fields=['created_at'], name='metrics_met_created_5eb216_idx'),
        ),
    ]
