# Generated by Django 5.2.6 on 2026-05-15 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_metricevent_metrics_met_created_5eb216_idx'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MetricEvent',
            new_name='MetricRecord',
        ),
        migrations.RenameIndex(
            model_name='metricrecord',
            new_name='metrics_met_event_t_fda89a_idx',
            old_name='metrics_met_event_t_2aed90_idx',
        ),
        migrations.RenameIndex(
            model_name='metricrecord',
            new_name='metrics_met_created_86dfe5_idx',
            old_name='metrics_met_created_5eb216_idx',
        ),
    ]
