# Generated by Django 5.2.6 on 2026-09-15 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0005_rename_metricevent_metricrecord_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metricrecord',
            options={'ordering': ['-created_at']},
        ),
    ]
