# Generated by Django 5.2.6 on 2026-02-12 00:34

import apps.uploads.utils.path
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=250, upload_to=apps.uploads.utils.path.get_upload_path)),
                ('original_filename', models.CharField(max_length=250)),
                ('mime_type', models.CharField(max_length=100)),
                ('hash_sha256', models.CharField(editable=False, max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[a-fA-F0-9]{64}$')])),
                ('size', models.PositiveIntegerField(editable=False)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('purpose', models.CharField(choices=[('avatar', 'Avatar'), ('thumbnail', 'Thumbnail'), ('attachment', 'Attachment')], default='attachment', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('inherit', 'Inherit')], db_index=True, default='inherit', max_length=10)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hash_sha256'], name='uploads_upl_hash_sh_c6e211_idx'), models.Index(fields=['uploaded_by', 'created_at'], name='uploads_upl_uploade_e88e4a_idx')],
            },
        ),
    ]
