# Generated by Django 5.2.6 on 2026-02-16 22:46

import apps.uploads.storage.factory
import apps.uploads.utils.path
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(max_length=500, storage=apps.uploads.storage.factory.get_media_storage, upload_to=apps.uploads.utils.path.get_upload_path),
        ),
        migrations.AlterField(
            model_name='upload',
            name='hash_sha256',
            field=models.CharField(db_index=True, editable=False, max_length=64, validators=[django.core.validators.RegexValidator('^[a-fA-F0-9]{64}$')]),
        ),
    ]
