# Generated by Django 5.2.6 on 2026-09-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], db_index=True, default='private', max_length=16),
        ),
    ]
