# Generated by Django 5.2.6 on 2025-10-07 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='upload',
            index=models.Index(fields=['file_type'], name='uploads_upl_file_ty_74b393_idx'),
        ),
        migrations.AddIndex(
            model_name='upload',
            index=models.Index(fields=['uploaded_by', 'created_at'], name='uploads_upl_uploade_e88e4a_idx'),
        ),
        migrations.AddIndex(
            model_name='upload',
            index=models.Index(fields=['hash_md5'], name='uploads_upl_hash_md_73d199_idx'),
        ),
    ]
