# Generated by Django 5.2.6 on 2025-10-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_alter_upload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='purpose',
            field=models.CharField(blank=True, choices=[('avatar', 'Avatar'), ('thumbnail', 'Thumbnail'), ('attachment', 'Attachment')], help_text='Optional: defines the purpose of this file for traceability', max_length=20),
        ),
    ]
