# Generated by Django 5.2.6 on 2026-01-25 03:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0007_remove_upload_uploads_upl_hash_md_73d199_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='upload',
            name='uploads_upl_file_ty_74b393_idx',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='is_public',
        ),
        migrations.AddField(
            model_name='upload',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('inherit', 'Inherit')], db_index=True, default='inherit', max_length=10),
        ),
        migrations.AlterField(
            model_name='upload',
            name='hash_sha256',
            field=models.CharField(editable=False, max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[a-fA-F0-9]{64}$')]),
        ),
        migrations.AlterField(
            model_name='upload',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='upload',
            name='mime_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='upload',
            name='purpose',
            field=models.CharField(choices=[('avatar', 'Avatar'), ('thumbnail', 'Thumbnail'), ('attachment', 'Attachment')], default='attachment', max_length=20),
        ),
        migrations.AlterField(
            model_name='upload',
            name='size',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='upload',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
